/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cwh_NVR_NVRNative */

#ifndef _Included_cwh_NVR_NVRNative
#define _Included_cwh_NVR_NVRNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cwh_NVR_NVRNative
 * Method:    login
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cwh_NVR_NVRNative_login
  (JNIEnv *, jclass);

/*
 * Class:     cwh_NVR_NVRNative
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cwh_NVR_NVRNative_init
  (JNIEnv *, jclass);

/*
 * Class:     cwh_NVR_NVRNative
 * Method:    logout
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cwh_NVR_NVRNative_logout
  (JNIEnv *, jclass);

/*
 * Class:     cwh_NVR_NVRNative
 * Method:    cleanUp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cwh_NVR_NVRNative_cleanUp
  (JNIEnv *, jclass);

/*
 * Class:     cwh_NVR_NVRNative
 * Method:    getLogs
 * Signature: (IIIIIIIIIIIII)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_cwh_NVR_NVRNative_getLogs
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     cwh_NVR_NVRNative
 * Method:    time2VideoPath
 * Signature: (IIIIIIIIIIIIIIIIIILjava/lang/String;Lcwh/NVR/play/PlayCallback;)V
 */
JNIEXPORT void JNICALL Java_cwh_NVR_NVRNative_time2VideoPath
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jstring, jobject);

/*
 * Class:     cwh_NVR_NVRNative
 * Method:    getDevTime
 * Signature: (IIIII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cwh_NVR_NVRNative_getDevTime
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
